### ISSUE TITLE
swig interface declared that is not defined

### ISSUE THREAD

**Issue by douglasgscofield** [bcgsc/btl_bloomfilter#4]
`swig/BloomFilter.i` is defining an interface to `insert()` and `contains()` methods accepting `const char*` but `BloomFilter.hpp` doesn't contain those definitions, only ones involving `size_t` reference or pointer.  The tests are expecting to do thinks like `insert("ATCG")`.

**Comment by JustinChu** [comment]
Thanks for the report. It seems that in my attempt to decouple parts of the code I broke the swig module.

**Comment by JustinChu** [comment]
Okay I push a fix: f02a7d7cb9b238ec1b429baa092229e5a84fe0ed.

I've run the internal tests, let me know if you have any problems, Douglas.

Thanks.
