### ISSUE TITLE
Add some sort of version check between hash function version changes

### ISSUE THREAD

**Issue by JustinChu** [bcgsc/btl_bloomfilter#6]

**Comment by JustinChu** [comment]
@lcoombe actually had another version error thing occur today with my release of BBT 2.2.0 (which uses the new ntHash). She used an old filter that caused an unexpected results.

@benvvalk @TheSeaOfRhun what are your thoughts today about this? Is there anything that I'm overlooking. Also how would this be implimented? Would the we just add an integer as the last field of the header?

**Comment by benvvalk** [comment]
Yep, it's that simple... just a single integer field in the file header.

For an example, search for "version" in this source file (Konnector Bloom filter IO code):

https://github.com/bcgsc/abyss/blob/d4b4b5d3091d90a4967180d987bd7168dbf04585/Bloom/Bloom.h

**Comment by benvvalk** [comment]
Thanks, @JustinChu!

**Comment by JustinChu** [comment]
@jowong4 Does the new counting bloom filter have a version number in the header? If so we can close this ticket.

**Comment by jowong4** [comment]
No. Not at the moment. I will add add a version number variable to it soon, after I finish bug fixing the read and write filter functions

**Comment by jowong4** [comment]
#15  
The above pull request includes version number variable in the header which is currently set to 2.

**Comment by jowong4** [comment]
version is check now part of the magic header string
